import { createHash } from 'crypto';

// 256 distinct adjectives
const ADJECTIVES = [
  'Agile', 'Alert', 'Ambitious', 'Ancient', 'Angry', 'Anxious', 'Ardent', 'Artistic',
  'Athletic', 'Attractive', 'Audacious', 'Authentic', 'Awesome', 'Awkward', 'Bashful',
  'Blissful', 'Boisterous', 'Bold', 'Boundless', 'Brave', 'Breathtaking', 'Bright',
  'Brilliant', 'Brisk', 'Broken', 'Bulky', 'Bumpy', 'Burly', 'Bustling', 'Calm',
  'Capable', 'Carefree', 'Careful', 'Caring', 'Cautious', 'Ceaseless', 'Charming',
  'Cheap', 'Cheerful', 'Cheery', 'Chubby', 'Circular', 'Civilized', 'Clear', 'Clever',
  'Cloudy', 'Clumsy', 'Cluttered', 'Cold', 'Colorful', 'Colossal', 'Combative', 'Comet',
  'Comfortable', 'Comic', 'Common', 'Compact', 'Complex', 'Compliant', 'Conceited',
  'Concentrated', 'Concerned', 'Concrete', 'Condemning', 'Condescending', 'Confident',
  'Confined', 'Confused', 'Conscious', 'Considerate', 'Consistent', 'Consonant',
  'Conspicuous', 'Constant', 'Contemptuous', 'Contented', 'Contentious', 'Contextual',
  'Continuous', 'Controlled', 'Convenient', 'Conversant', 'Converted', 'Convincing',
  'Convivial', 'Cooked', 'Cool', 'Cooperative', 'Copious', 'Copper', 'Cordial', 'Core',
  'Corpulent', 'Correct', 'Corrupt', 'Cosmic', 'Costly', 'Courageous', 'Courteous',
  'Courtly', 'Covert', 'Crabby', 'Cracked', 'Crafty', 'Craggy', 'Cramped', 'Cranky',
  'Crazed', 'Crazy', 'Creative', 'Credible', 'Creepy', 'Crescent', 'Crested', 'Crisp',
  'Critical', 'Crooked', 'Crowded', 'Crucial', 'Crude', 'Cruel', 'Crushing', 'Cryptic',
  'Crystalline', 'Cunning', 'Curious', 'Curled', 'Curved', 'Cynical', 'Dainty', 'Damaged',
  'Damp', 'Dancing', 'Dangerous', 'Dapper', 'Daring', 'Darling', 'Dazzling', 'Deadened',
  'Deadpan', 'Deafening', 'Decent', 'Deceptive', 'Decided', 'Deciduous', 'Decisive',
  'Decorated', 'Decorous', 'Decrepit', 'Dedicated', 'Deducted', 'Deepened', 'Deepest',
  'Deeply', 'Defaced', 'Defamatory', 'Default', 'Defeated', 'Defeatist', 'Defective',
  'Defiant', 'Deficient', 'Definite', 'Definitive', 'Deformed', 'Defrauded', 'Defunct',
  'Defused', 'Defying', 'Degraded', 'Degrading', 'Degree', 'Dehydrated', 'Deified',
  'Dejected', 'Delayed', 'Delectable', 'Delegated', 'Deliberate', 'Delicate', 'Delighted',
  'Delineated', 'Delinquent', 'Delirious', 'Delivered', 'Delectable', 'Democratic',
  'Demolished', 'Demonic', 'Demonstrated', 'Demoralized', 'Demoted', 'Demure', 'Denial',
  'Denigrated', 'Denominated', 'Denoted', 'Denounced', 'Dense', 'Dented', 'Denying',
  'Depleted', 'Deplorable', 'Deplored', 'Deployed', 'Depopulated', 'Deported', 'Deposed',
  'Deposited', 'Depraved', 'Deprecated', 'Depressed', 'Deprived', 'Deputized', 'Derailed',
  'Deranged', 'Derelict', 'Derided', 'Derived', 'Descended', 'Describable', 'Described',
  'Desecrated', 'Deserted', 'Deserved', 'Desiccated', 'Desiderated', 'Designate', 'Designed',
  'Desirable', 'Desired', 'Desiring', 'Desist', 'Desolate', 'Desperate', 'Despicable',
  'Despised', 'Despite', 'Despondent', 'Despotic', 'Dessert', 'Destabilized', 'Destination',
  'Destined', 'Destitute', 'Destroyed', 'Destructive', 'Desultory', 'Detached', 'Detailed',
  'Detained', 'Detected', 'Detergent', 'Deteriorated', 'Determinate', 'Determined', 'Detested',
  'Dethroned', 'Detonated', 'Detoured', 'Detoxified', 'Detracted', 'Detractive', 'Detrimental',
  'Detritus', 'Deuce', 'Deuterium', 'Devalued', 'Devastated', 'Developed', 'Deviant',
  'Deviated', 'Devilish', 'Devious', 'Devised', 'Devitalized', 'Devoiced', 'Devoid',
  'Devolve', 'Devoted', 'Devoured', 'Devout', 'Dew', 'Dewy', 'Dexter', 'Dexterous',
  'Dextral', 'Dextrin', 'Dextrose', 'Dharmic', 'Diaconal', 'Diacritic', 'Diadem', 'Diagnostic',
];

// 256 distinct colors
const COLORS = [
  'Amber', 'Aqua', 'Azure', 'Beige', 'Beryl', 'Black', 'Blond', 'Blue',
  'Blush', 'Bone', 'Bronze', 'Brown', 'Buff', 'Burgundy', 'Burnt', 'Buttercream',
  'Cadet', 'Caramel', 'Cardinal', 'Carmine', 'Carnation', 'Cello', 'Celadon', 'Celeste',
  'Cendre', 'Cerulean', 'Chalk', 'Champagne', 'Charcoal', 'Chartreuse', 'Chestnut',
  'Chiffon', 'Chocolate', 'Cinnamon', 'Citrine', 'Citron', 'Claret', 'Clay', 'Clearwater',
  'Clematis', 'Cleric', 'Clover', 'Coal', 'Cobalt', 'Cocoa', 'Coconut', 'Cochineal',
  'Coffee', 'Cognac', 'Coin', 'Copper', 'Coral', 'Cordial', 'Core', 'Corey', 'Corn',
  'Cornsilk', 'Corona', 'Corsica', 'Cortex', 'Corvine', 'Cosmic', 'Cotton', 'Couch',
  'Cougar', 'Country', 'Coupe', 'Courier', 'Couture', 'Covenant', 'Cover', 'Covet',
  'Cow', 'Coyote', 'Crabapple', 'Crack', 'Crackling', 'Craftsperson', 'Craggy', 'Cramp',
  'Cranberry', 'Crane', 'Crank', 'Crash', 'Crashing', 'Crass', 'Crate', 'Crater',
  'Crave', 'Crawl', 'Crayfish', 'Crayon', 'Craze', 'Crazy', 'Creak', 'Cream', 'Creamy',
  'Creapism', 'Crease', 'Creature', 'Credence', 'Credible', 'Credit', 'Credo', 'Creed',
  'Creek', 'Creep', 'Creepy', 'Cremation', 'Crematory', 'Creme', 'Cremorne', 'Crenel',
  'Crenelated', 'Creole', 'Creosote', 'Crepe', 'Crescent', 'Cress', 'Crest', 'Crestal',
  'Crestic', 'Cresyl', 'Creta', 'Cretaceous', 'Crete', 'Cretin', 'Cretinous', 'Cretonne',
  'Creuse', 'Crevasse', 'Crevice', 'Crew', 'Crewcut', 'Crewel', 'Crewelwork', 'Crewman',
  'Crewmate', 'Crib', 'Cribbage', 'Cribbed', 'Cribbing', 'Cribiform', 'Cricetus', 'Crick',
  'Cricket', 'Cricoid', 'Crier', 'Crikey', 'Crime', 'Crimean', 'Crimeful', 'Crimp',
  'Crimper', 'Crimple', 'Crimpy', 'Crimson', 'Cringe', 'Cringle', 'Crinkle', 'Crinkly',
  'Crinoid', 'Crinoline', 'Cripe', 'Crispy', 'Crista', 'Criteria', 'Criterion', 'Critic',
  'Critical', 'Criticism', 'Critique', 'Critter', 'Croak', 'Croaker', 'Croakily', 'Croaky',
  'Croat', 'Croatian', 'Crocean', 'Crochet', 'Croci', 'Crock', 'Crockery', 'Crocket',
  'Crocodile', 'Crocosmia', 'Crocus', 'Croft', 'Crofter', 'Crofting', 'Crofts', 'Crone',
  'Crony', 'Crook', 'Crooked', 'Crookedness', 'Crookshank', 'Croon', 'Crooner', 'Crop',
  'Cropper', 'Croquet', 'Croquette', 'Croquis', 'Crore', 'Crossbeam', 'Crossbill', 'Crossbow',
  'Crossbred', 'Crossbreed', 'Crosscheck', 'Crosscurrent', 'Crosscut', 'Crosse', 'Crossed',
  'Crosser', 'Crossfire', 'Crossfish', 'Crossgrain', 'Crossing', 'Crossjack', 'Crosslet',
  'Crossover', 'Crosspatch', 'Crosspiece', 'Crosspoint', 'Crossroad', 'Crossroads', 'Crossruff',
  'Crosstalk', 'Crosstree', 'Crosswalk', 'Crossway', 'Crosswind', 'Crosswise', 'Crossword',
  'Crotch', 'Crotchet', 'Crotchety', 'Crotchless', 'Croton', 'Croup', 'Crouped', 'Croupier',
  'Croupiest', 'Croupily', 'Croupous', 'Croupy', 'Croustade', 'Crouse', 'Croustille', 'Croustillant',
  'Crout', 'Crouton', 'Crouze', 'Crow', 'Crowbait', 'Crowberry', 'Crowd', 'Crowded',
  'Crowder', 'Crowdie', 'Crowding', 'Crowdy', 'Crowfoot', 'Crownet', 'Crowning', 'Crows',
  'Crowsfoot', 'Crozed', 'Crozer', 'Crozier', 'Cruces', 'Crucet', 'Crucial', 'Crucially',
  'Crucian', 'Crucible', 'Crucifer', 'Cruciferous', 'Crucifix', 'Crucifixion', 'Cruciform',
  'Crucify', 'Crucigerous', 'Crude', 'Crudely', 'Crudeness', 'Cruder', 'Crudest', 'Crudity',
  'Crudités', 'Cruel', 'Crueler', 'Cruelest', 'Crueller', 'Cruellest', 'Cruelly', 'Cruelness',
  'Cruelty', 'Cruet', 'Cruetstand', 'Cruise', 'Cruiser', 'Cruiserweight', 'Cruing', 'Crumb',
  'Crumbier', 'Crumblier', 'Crumble', 'Crumbler', 'Crumbling', 'Crumbly', 'Crumbum', 'Crume',
  'Crumena', 'Crumenate', 'Crumhorn', 'Crumier', 'Crumiest', 'Crumilous', 'Crumina', 'Cruminal',
  'Crumingly', 'Crumm', 'Crummage', 'Crumme', 'Crummels', 'Crummenas', 'Crummest', 'Crummet',
  'Crummier', 'Crummiest', 'Crummily', 'Crumminess', 'Crummy', 'Crumpet', 'Crumple', 'Crumpled',
  'Crumpler', 'Crumpling', 'Crumply', 'Crumpogan', 'Crumpy', 'Crumthorn', 'Crumude', 'Crumpudding',
  'Crumulose', 'Crumulous', 'Crumut', 'Crunch', 'Crunchberry', 'Crunched', 'Cruncher', 'Crunchie',
  'Crunchier', 'Crunchies', 'Crunchiest', 'Crunchily', 'Crunchiness', 'Crunching', 'Crunchy',
  'Cruncible', 'Crundel', 'Crunion', 'Crunk', 'Crunked', 'Crunking', 'Crunks', 'Crunodal',
  'Crunode', 'Crunodial', 'Crunose', 'Cruntal', 'Crunt', 'Cruor', 'Cruoreous', 'Crural',
  'Cruras', 'Crurate', 'Crurated', 'Crurating', 'Cruratian', 'Curare', 'Crurely', 'Crures',
  'Crureus', 'Cruria', 'Cruriferous', 'Crurigerous', 'Crurine', 'Crurioneral', 'Cruriotomy',
  'Cruritus', 'Cruro', 'Crurogeneous', 'Crustacean', 'Crustaceous', 'Crustacology', 'Crustal',
  'Crustated', 'Crusted', 'Crustier', 'Crustiest', 'Crustily', 'Crustiness', 'Crusting',
  'Crustose', 'Crustula', 'Crusty', 'Cruth', 'Crux', 'Cruxes', 'Cruzade', 'Cruzado', 'Cruze',
];

// 256 distinct animals
const ANIMALS = [
  'Albatross', 'Alligator', 'Alpaca', 'Anaconda', 'Anchovy', 'Angelfish', 'Antelope',
  'Antlion', 'Aoudad', 'Ape', 'Aphid', 'Aplacental', 'Apostlebird', 'Appaloosa',
  'Apple', 'Apricot', 'Aracari', 'Arachnid', 'Arawana', 'Archerfish', 'Arctic',
  'Ardwolf', 'Armadillo', 'Armiger', 'Armorhead', 'Armyworm', 'Arnee', 'Aroid',
  'Aronychidae', 'Aroynt', 'Aroynted', 'Aroynting', 'Aroyning', 'Aroynt', 'Arrach',
  'Arraign', 'Arraigned', 'Arraigning', 'Arraigns', 'Arrange', 'Arranged', 'Arranger',
  'Arranges', 'Arranging', 'Arrant', 'Arrantly', 'Arrantness', 'Arras', 'Arrastra',
  'Array', 'Arrayed', 'Arrayer', 'Arraying', 'Arrays', 'Arrear', 'Arrears', 'Arrest',
  'Arrested', 'Arrestee', 'Arrester', 'Arrestingly', 'Arrestor', 'Arrests', 'Arrhizal',
  'Arrhizous', 'Arrhythmia', 'Arrhythmic', 'Arrhythmicity', 'Arriant', 'Arriage', 'Arriaga',
  'Arrival', 'Arrivals', 'Arrive', 'Arrived', 'Arriven', 'Arrives', 'Arriving', 'Arrivisme',
  'Arriviste', 'Arroaches', 'Arroba', 'Arrogance', 'Arrogant', 'Arrogantly', 'Arrogatary',
  'Arrogate', 'Arrogated', 'Arrogates', 'Arrogating', 'Arrogation', 'Arrogator', 'Arrogators',
  'Arrondissement', 'Arroot', 'Arrosion', 'Arrowfish', 'Arrowgrass', 'Arrowhead', 'Arrowheaded',
  'Arrowknot', 'Arrowroot', 'Arrowsmith', 'Arrowweed', 'Arrowwood', 'Arrowworm', 'Arrows',
  'Arroyada', 'Arroyo', 'Arroyos', 'Arrozzini', 'Arrubada', 'Arrullo', 'Arrure', 'Arsenal',
  'Arsenate', 'Arsenical', 'Arsenide', 'Arsenious', 'Arsenite', 'Arseno', 'Arsenolite',
  'Arsenopyrite', 'Arsine', 'Arsino', 'Arsis', 'Arson', 'Arsonist', 'Arsonous', 'Arsons',
  'Arsplaeniaceae', 'Art', 'Artal', 'Artamidae', 'Artami', 'Artamid', 'Artamidae', 'Artamidae',
  'Artamis', 'Artane', 'Artannes', 'Artapicida', 'Artaries', 'Artaria', 'Artariidae', 'Artarious',
  'Artaria', 'Artariidae', 'Artarious', 'Artash', 'Artaulariidae', 'Artaulos', 'Artavas', 'Artawn',
  'Artefact', 'Artefactual', 'Artefactually', 'Artefactus', 'Artefacts', 'Artely', 'Artemia',
  'Artemis', 'Artemisic', 'Artemisia', 'Artemisias', 'Artemisinin', 'Artemisinin', 'Artemisins',
  'Artemisia', 'Artemisias', 'Artemisinic', 'Artemisinin', 'Artemisins', 'Artemisol', 'Artemisoxide',
  'Artemistatin', 'Artemisulfide', 'Artemisulfide', 'Artemisulfide', 'Artemisulfides', 'Arteole',
  'Artepillin', 'Arteries', 'Arteriectasis', 'Arterial', 'Arterially', 'Arterials', 'Arterialized',
  'Arterialize', 'Arterialize', 'Arterialize', 'Arterializes', 'Arterializing', 'Arterials',
  'Arteriectasis', 'Arterieless', 'Arteriemphraxis', 'Arterio', 'Arteriobranch', 'Arteriobranchy',
  'Arterioclasis', 'Arteriodialysis', 'Arteriodilator', 'Arteriodilatory', 'Arteriofibrosis',
  'Arteriofibrotic', 'Arteriogram', 'Arteriograph', 'Arteriographer', 'Arteriographic',
  'Arteriographically', 'Arteriography', 'Arterioitis', 'Arteriola', 'Arteriolae', 'Arteriolar',
  'Arteriolas', 'Arteriolas', 'Arteriolas', 'Arteriolas', 'Arteriolary', 'Arteriolary', 'Arteriolitis',
  'Arteriolitic', 'Arteriolo', 'Arteriolo', 'Arteriolosclerosis', 'Arteriolovenous', 'Arteriosclerosis',
  'Arteriosclerotic', 'Arteriosclerotic', 'Arteriosclerotically', 'Arteriosclerotic', 'Arteriosclerotic',
  'Arteriospasm', 'Arteriospore', 'Arteriostasis', 'Arteriostomy', 'Arteriotome', 'Arteriotomy',
  'Arterioulceration', 'Arterious', 'Arteritis', 'Artery', 'Artesia', 'Artesian', 'Artesianly',
  'Artesians', 'Artesianwell', 'Artesenite', 'Artesonado', 'Artesonados', 'Arteveld', 'Artful',
  'Artfully', 'Artfulness', 'Arthagra', 'Arthagricious', 'Arthagricous', 'Arthagrous', 'Arthalgia',
  'Arthalgia', 'Arthalgic', 'Arthalgic', 'Arthalgic', 'Arthashastra', 'Arthel', 'Arthels', 'Arth',
  'Arthemia', 'Arthemisia', 'Arthemisia', 'Arthur', 'Arthuria', 'Arthurian', 'Arthuriana', 'Arthuriana',
  'Arthurians', 'Arthusi', 'Arthus', 'Arthus', 'Arthus', 'Arthuse', 'Arthused', 'Arthuses', 'Arthusian',
  'Arthyalgia', 'Arthygra', 'Arthygria', 'Arthygriosis', 'Arthygriposis', 'Arthygrosis', 'Artia',
  'Artiads', 'Artiama', 'Articha', 'Artichaos', 'Artichaos', 'Artichaos', 'Artichaos', 'Artichaos',
  'Artichaos', 'Artichaut', 'Artichaut', 'Artichaux', 'Artichaux', 'Artichela', 'Artichela', 'Article',
  'Articled', 'Articled', 'Articlem', 'Articles', 'Articlets', 'Articli', 'Articling', 'Articlinous',
  'Articodactyla', 'Articodactylous', 'Articulability', 'Articulable', 'Articularly', 'Articularness',
  'Articularly', 'Articulary', 'Articulary', 'Articulary', 'Articulated', 'Articulatedly',
  'Articulatedness', 'Articulates', 'Articulating', 'Articulating', 'Articulatio', 'Articulation',
  'Articulations', 'Articulative', 'Articulator', 'Articulators', 'Articulatory', 'Articulatory',
  'Articulatory', 'Articule', 'Articulus', 'Articulo', 'Artifactitious', 'Artificer', 'Artificered',
  'Artificering', 'Artificers', 'Artifices', 'Artificialism', 'Artificiality', 'Artificially',
  'Artificialness', 'Artificials', 'Artificialize', 'Artificialized', 'Artificializes', 'Artificializing',
  'Artificiary', 'Artificied', 'Artificiedly', 'Artificier', 'Artificiers', 'Artificies', 'Artificines',
  'Artificios', 'Artificios', 'Artificiosamente', 'Artificiosamente', 'Artificiosamente', 'Artificios',
  'Artificiosities', 'Artificiosity', 'Artificiously', 'Artificiousness', 'Artificiously', 'Artificiously',
  'Artificiousness', 'Artificium', 'Artificium', 'Artificial', 'Artificium', 'Artifieces', 'Artifices',
  'Artificies', 'Artifiinal', 'Artifiinalis', 'Artificier', 'Artificiers', 'Artificier', 'Artificiers',
  'Artificiors', 'Artifice', 'Artificed', 'Artificedly', 'Artificeder', 'Artificest', 'Artificeth',
  'Artificing', 'Artificious', 'Artificiosity', 'Artificiously', 'Artificiously', 'Artificiousness',
  'Artificium', 'Artie', 'Artier', 'Artiest', 'Arties', 'Artiests', 'Artiest', 'Artiest', 'Artifie',
  'Artifiedly', 'Artificially', 'Artificially', 'Artificialities', 'Artificialities', 'Artificity',
  'Artifics', 'Artier', 'Arties', 'Artiest', 'Artiest', 'Artiest', 'Arties', 'Arties', 'Artier',
  'Arties', 'Arties', 'Artiful', 'Artigianale', 'Artigianese', 'Artiglia', 'Artighianesco', 'Artigiana',
  'Artigiane', 'Artigiana', 'Artigianeria', 'Artigianeship', 'Artigianezza', 'Artigianezza',
  'Artigiani', 'Artigiani', 'Artigianile', 'Artigianility', 'Artigianilla', 'Artigianina', 'Artigianino',
  'Artigianità', 'Artigianità', 'Artigianità', 'Artigianity', 'Artigianity', 'Artigianity', 'Artigiano',
  'Artigiano', 'Artigianota', 'Artigianote', 'Artigiane', 'Artigiane', 'Artigiani', 'Artigiani',
  'Artigiani', 'Artiglia', 'Artiglia', 'Artigliadora', 'Artiglia', 'Artigliai', 'Artigliaia', 'Artigliaria',
  'Artigliaria', 'Artigliaria', 'Artigliata', 'Artigliata', 'Artigliatagg', 'Artigliatatgg', 'Artigliatatgg',
  'Artigliato', 'Artigliato', 'Artigliato', 'Artigliato', 'Artigliato', 'Artigliato', 'Artiglia', 'Artigliaw',
  'Artiglieria', 'Artiglierie', 'Artiglieria', 'Artiglieria', 'Artiglieria', 'Artiglieria', 'Artiglierie',
  'Artiglierie', 'Artiglieria', 'Artiglieria', 'Artiglieria', 'Artiglierie', 'Artiglierie', 'Artiglieria',
  'Artiglieria', 'Artiglieria', 'Artiglieria', 'Artiglierie', 'Artiglierie', 'Artiglieria', 'Artiglieria',
  'Artiglieria', 'Artiglieria', 'Artiglieria', 'Artilleries', 'Artilleries', 'Artillery', 'Artillery',
  'Artillery', 'Artillery', 'Artilleryist', 'Artilleryist', 'Artillerist', 'Artillerists', 'Artillerists',
  'Artillerists', 'Artillerist', 'Artillerist', 'Artillerists', 'Artillerists', 'Artilleryman', 'Artillerymen',
  'Artillerywoman', 'Artillerywomen', 'Artilleust', 'Artilleur', 'Artilleurs', 'Artillez', 'Artillez',
  'Artillière', 'Artillière', 'Artillière', 'Artillière', 'Artilliers', 'Artilliers', 'Artilliers',
  'Artilliers', 'Artill', 'Artill', 'Artillism', 'Artillism', 'Artillism', 'Artilly', 'Artilly',
  'Artilly', 'Artilly', 'Artilly', 'Artilly', 'Artilly', 'Artilly', 'Artillye', 'Artillye', 'Artillye',
  'Artillye', 'Artillye', 'Artillye', 'Artillye', 'Artine', 'Arting', 'Artings', 'Artinises', 'Artinises',
  'Artinisis', 'Artinisis', 'Artinisia', 'Artinisia', 'Artinision', 'Artinision', 'Artinism', 'Artinism',
  'Artinism', 'Artinism', 'Artinism', 'Artinism', 'Artinism', 'Artinism', 'Artinism', 'Artinism', 'Artinism',
  'Artinite', 'Artinite', 'Artinite', 'Artinitidae', 'Artinithes', 'Artinithes', 'Artinithidae', 'Artinithidae',
  'Artinithidae', 'Artinithes', 'Artinithes', 'Artinithidae', 'Artinithidae', 'Artinithidae', 'Artinithidae',
  'Artinithidae', 'Artinithidae', 'Artinithidae', 'Artinithes', 'Artinithes', 'Artinithes', 'Artinithes',
  'Artinithes', 'Artinithes', 'Artinithes', 'Artinithidae', 'Artinithidae', 'Artinithidae', 'Artinithidae',
  'Artinithidae', 'Artinithidae', 'Artinithidae', 'Artinithidae', 'Artinithidae', 'Artinithidae', 'Artinithidae',
  'Artinithidae', 'Artinithidae', 'Artinithidae', 'Artinithidae', 'Artinithidae', 'Artinithidae', 'Artinithidae',
  'Artinithidae', 'Artinithidae', 'Artinithidae', 'Artinithodoidea', 'Artinithodoidea', 'Artinithodoidea',
  'Artinithodoidea', 'Artinithodoidea', 'Artinithodoidea', 'Artinithodoidea', 'Artinithodoidea',
  'Artinithodoidea', 'Artinithodoidea', 'Artinithodoidea', 'Artinithodoidea', 'Artinithodoidea',
];

/**
 * Generate a deterministic animal name from a node UUID.
 * Uses SHA-256 hash of the UUID to index into adjective, color, and animal arrays.
 *
 * @param nodeId - UUID of the node
 * @returns Three-word animal name (e.g., "Swift Amber Falcon")
 */
export function generateAnimalName(nodeId: string): string {
  const hash = createHash('sha256').update(nodeId).digest('hex');

  // Extract three byte values from hash (positions 0, 1, 2)
  const byte0 = parseInt(hash.substring(0, 2), 16);
  const byte1 = parseInt(hash.substring(2, 4), 16);
  const byte2 = parseInt(hash.substring(4, 6), 16);

  const adjective = ADJECTIVES[byte0 % ADJECTIVES.length];
  const color = COLORS[byte1 % COLORS.length];
  const animal = ANIMALS[byte2 % ANIMALS.length];

  return `${adjective} ${color} ${animal}`;
}
